; SNV4 Font Builder custom PHP config
; Recommended PHP package:
; Official PHP 8.5.4 VS17 x64 Non Thread Safe ZIP
; Extract the FULL PHP ZIP into this bundle's php folder.

extension_dir = "./ext"
extension=zip

upload_max_filesize = 256M
post_max_size = 256M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
max_file_uploads = 20
output_buffering = On
display_errors = On
log_errors = Off
